// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAowlBpYoPUCt-UwnowVAkRpZ0h5vcmE6c',
    appId: '1:288849460598:web:14875de1006f7bfcaa0e57',
    messagingSenderId: '288849460598',
    projectId: 'doctor-appointment-fadb3',
    authDomain: 'doctor-appointment-fadb3.firebaseapp.com',
    storageBucket: 'doctor-appointment-fadb3.firebasestorage.app',
    measurementId: 'G-8E62H25NW7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBh5vHM10BkYCDnXQhWUQqndHcDukUthPI',
    appId: '1:288849460598:android:987e5242739489e8aa0e57',
    messagingSenderId: '288849460598',
    projectId: 'doctor-appointment-fadb3',
    storageBucket: 'doctor-appointment-fadb3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxZXl_OegRE6KJJI9w9XExUc0ts-cDuDk',
    appId: '1:288849460598:ios:8b689cd14d22d188aa0e57',
    messagingSenderId: '288849460598',
    projectId: 'doctor-appointment-fadb3',
    storageBucket: 'doctor-appointment-fadb3.firebasestorage.app',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxZXl_OegRE6KJJI9w9XExUc0ts-cDuDk',
    appId: '1:288849460598:ios:8b689cd14d22d188aa0e57',
    messagingSenderId: '288849460598',
    projectId: 'doctor-appointment-fadb3',
    storageBucket: 'doctor-appointment-fadb3.firebasestorage.app',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAowlBpYoPUCt-UwnowVAkRpZ0h5vcmE6c',
    appId: '1:288849460598:web:073cb1dfc7a924daaa0e57',
    messagingSenderId: '288849460598',
    projectId: 'doctor-appointment-fadb3',
    authDomain: 'doctor-appointment-fadb3.firebaseapp.com',
    storageBucket: 'doctor-appointment-fadb3.firebasestorage.app',
    measurementId: 'G-YDNHM2B2RD',
  );
}
